name: Create Checksum POC

on:
  push:
    branches:
      - Poc-test
  workflow_dispatch:

jobs:
  checksum:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create artifact
        run: echo "hello" > artifact.txt

      - name: Generate checksum
        run: sha256sum artifact.txt > checksum.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: artifact.txt

      - name: Upload checksum
        uses: actions/upload-artifact@v4
        with:
          name: artifact-checksum
          path: checksum.txt
