name: POC Deployment Policy 
on:
 push:
   branches:
     - Poc-test
 workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest 
    environment: Poc-env1
    steps: 
       - name: Simulated deploy
         run : echo " Deploying to protect environment "
